version: '3.8'

services:
  extractor:
    build: ./extractor
    container_name: extractor
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  embeddings:
    build: ./embeddings
    container_name: embeddings
    ports:
      - "5002:5002"
    volumes:
      - ./data:/app/data
    env_file:
      - .env

  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    env_file:
      - .env

volumes:
  data:
