version: '3.8'

services:
  extractor:
    build: ./src/extractor
    container_name: extractor
    volumes:
      - ./data:/app/data
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1

  embeddings:
    build: ./src/embeddings
    container_name: embeddings
    volumes:
      - ./data:/app/data
    depends_on:
      - extractor
    ports:
      - "5002:5002"
    env_file:
      - .env

  api:
    build: ./src/api
    container_name: api
    depends_on:
      - embeddings
    ports:
      - "5000:5000"
    env_file:
      - .env

volumes:
  data:
